package inmobiliaria23.vistas;

import inmobiliaria23.entidades.InternaljFrameImagen;
import inmobiliaria23.entidades.panelesImagenes;
import java.awt.Image;

/**
 *
 * @author Administrador
 */
public class contratoDeAlquiler extends InternaljFrameImagen {

    private panelesImagenes pi = new panelesImagenes();

    public contratoDeAlquiler() {
        initComponents();
        this.setSize(1024, 770);

        this.setImage("/inmobiliaria23/recursos/FondoNaranja.jpg");
        //this.setImage("/inmobiliaria23/recursos/FondoGrandiet.jpg");
        //this.setImage("/inmobiliaria23/recursos/FondoMadera.jpg");

        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextID = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        DatosInquilinos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextIdContratoAlq = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextIDInmuebleContratoAlq = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextIDInquilinoContratoAlq = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jbtnAñadir = new inmobiliaria23.entidades.BotonNegro();
        jbModificar = new inmobiliaria23.entidades.BotonNegro();
        jbLimpiar = new inmobiliaria23.entidades.BotonNegro();
        jbBuscar = new inmobiliaria23.entidades.BotonNegro();
        jbEliminar = new inmobiliaria23.entidades.BotonRojo();
        jbGuardar = new inmobiliaria23.entidades.BotonVerde();
        jbSalir = new inmobiliaria23.entidades.BotonAzul();
        DatosInquilinos1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextMontoPesosContratoAlq = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFechaIniContratoAlq = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFechaFinContratoAlq = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextTelefonosPro3 = new javax.swing.JTextField();

        jTextID.setBackground(new java.awt.Color(236, 226, 200));
        jTextID.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextID.setForeground(new java.awt.Color(51, 51, 51));
        jTextID.setText(" ");
        jTextID.setBorder(null);
        jTextID.setPreferredSize(new java.awt.Dimension(165, 30));

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Roboto Bk", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(51, 51, 51));
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/Contracts.png"))); // NOI18N
        Titulo.setText("Contrato Alquiler");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        DatosInquilinos.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        DatosInquilinos.setOpaque(false);
        DatosInquilinos.setPreferredSize(new java.awt.Dimension(500, 390));
        DatosInquilinos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel1.setText("ID Contrato:");
        DatosInquilinos.add(jLabel1);

        jTextIdContratoAlq.setBackground(new java.awt.Color(236, 226, 200));
        jTextIdContratoAlq.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextIdContratoAlq.setForeground(new java.awt.Color(51, 51, 51));
        jTextIdContratoAlq.setText(" ");
        jTextIdContratoAlq.setBorder(null);
        jTextIdContratoAlq.setPreferredSize(new java.awt.Dimension(165, 30));
        jTextIdContratoAlq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdContratoAlqActionPerformed(evt);
            }
        });
        DatosInquilinos.add(jTextIdContratoAlq);

        jLabel2.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel2.setText("ID Inmueble:");
        DatosInquilinos.add(jLabel2);

        jTextIDInmuebleContratoAlq.setBackground(new java.awt.Color(236, 226, 200));
        jTextIDInmuebleContratoAlq.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextIDInmuebleContratoAlq.setForeground(new java.awt.Color(51, 51, 51));
        jTextIDInmuebleContratoAlq.setText(" ");
        jTextIDInmuebleContratoAlq.setBorder(null);
        jTextIDInmuebleContratoAlq.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos.add(jTextIDInmuebleContratoAlq);

        jLabel3.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel3.setText("ID Inquilino");
        DatosInquilinos.add(jLabel3);

        jTextIDInquilinoContratoAlq.setBackground(new java.awt.Color(236, 226, 200));
        jTextIDInquilinoContratoAlq.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextIDInquilinoContratoAlq.setForeground(new java.awt.Color(51, 51, 51));
        jTextIDInquilinoContratoAlq.setText(" ");
        jTextIDInquilinoContratoAlq.setBorder(null);
        jTextIDInquilinoContratoAlq.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos.add(jTextIDInquilinoContratoAlq);

        getContentPane().add(DatosInquilinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 1010, 40));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jbtnAñadir.setBorder(null);
        jbtnAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/nuevo.png"))); // NOI18N
        jbtnAñadir.setText(" NUEVO");
        jbtnAñadir.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jbtnAñadir.setPreferredSize(new java.awt.Dimension(120, 30));
        jbtnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAñadir);

        jbModificar.setBorder(null);
        jbModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/modificar.png"))); // NOI18N
        jbModificar.setText(" MODIFICAR");
        jbModificar.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jbModificar.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel1.add(jbModificar);

        jbLimpiar.setBorder(null);
        jbLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/LimpiarCampos.png"))); // NOI18N
        jbLimpiar.setText(" LIMPIAR");
        jbLimpiar.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jbLimpiar.setPreferredSize(new java.awt.Dimension(120, 30));
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jbLimpiar);

        jbBuscar.setBorder(null);
        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/buscar-interna.png"))); // NOI18N
        jbBuscar.setText(" BUSCAR");
        jbBuscar.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jbBuscar.setPreferredSize(new java.awt.Dimension(120, 30));
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jbBuscar);

        jbEliminar.setBorder(null);
        jbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/delete.png"))); // NOI18N
        jbEliminar.setText("ELIMINAR");
        jbEliminar.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jbEliminar.setPreferredSize(new java.awt.Dimension(120, 30));
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jbEliminar);

        jbGuardar.setBorder(null);
        jbGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/guardar.png"))); // NOI18N
        jbGuardar.setText("GUARDAR");
        jbGuardar.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jbGuardar.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel1.add(jbGuardar);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1000, 50));

        jbSalir.setBorder(null);
        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/exits.png"))); // NOI18N
        jbSalir.setText(" SALIR");
        jbSalir.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jbSalir.setPreferredSize(new java.awt.Dimension(120, 30));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 610, -1, -1));

        DatosInquilinos1.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        DatosInquilinos1.setOpaque(false);
        DatosInquilinos1.setPreferredSize(new java.awt.Dimension(500, 390));
        DatosInquilinos1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel11.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel11.setText("Monto en Pesos:");
        DatosInquilinos1.add(jLabel11);

        jTextMontoPesosContratoAlq.setBackground(new java.awt.Color(236, 226, 200));
        jTextMontoPesosContratoAlq.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextMontoPesosContratoAlq.setForeground(new java.awt.Color(51, 51, 51));
        jTextMontoPesosContratoAlq.setText(" ");
        jTextMontoPesosContratoAlq.setBorder(null);
        jTextMontoPesosContratoAlq.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos1.add(jTextMontoPesosContratoAlq);

        jLabel12.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel12.setText("Fecha Inicio:");
        DatosInquilinos1.add(jLabel12);

        jTextFechaIniContratoAlq.setBackground(new java.awt.Color(236, 226, 200));
        jTextFechaIniContratoAlq.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextFechaIniContratoAlq.setForeground(new java.awt.Color(51, 51, 51));
        jTextFechaIniContratoAlq.setText(" ");
        jTextFechaIniContratoAlq.setBorder(null);
        jTextFechaIniContratoAlq.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos1.add(jTextFechaIniContratoAlq);

        jLabel13.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel13.setText("Fecha Fin:");
        DatosInquilinos1.add(jLabel13);

        jTextFechaFinContratoAlq.setBackground(new java.awt.Color(236, 226, 200));
        jTextFechaFinContratoAlq.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextFechaFinContratoAlq.setForeground(new java.awt.Color(51, 51, 51));
        jTextFechaFinContratoAlq.setText(" ");
        jTextFechaFinContratoAlq.setBorder(null);
        jTextFechaFinContratoAlq.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos1.add(jTextFechaFinContratoAlq);

        jLabel14.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel14.setText("Estado:");
        DatosInquilinos1.add(jLabel14);

        jTextTelefonosPro3.setBackground(new java.awt.Color(236, 226, 200));
        jTextTelefonosPro3.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextTelefonosPro3.setForeground(new java.awt.Color(51, 51, 51));
        jTextTelefonosPro3.setText(" ");
        jTextTelefonosPro3.setBorder(null);
        jTextTelefonosPro3.setPreferredSize(new java.awt.Dimension(30, 30));
        DatosInquilinos1.add(jTextTelefonosPro3);

        getContentPane().add(DatosInquilinos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 1000, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAñadirActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
       

    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed

    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        jTextIdContratoAlq.setText("");
        jTextIDInmuebleContratoAlq.setText("");
        jTextIDInquilinoContratoAlq.setText("");
        jTextMontoPesosContratoAlq.setText("");
        jTextFechaIniContratoAlq.setText("");
        
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jTextIdContratoAlqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdContratoAlqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdContratoAlqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DatosInquilinos;
    private javax.swing.JPanel DatosInquilinos1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFechaFinContratoAlq;
    private javax.swing.JTextField jTextFechaIniContratoAlq;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextIDInmuebleContratoAlq;
    private javax.swing.JTextField jTextIDInquilinoContratoAlq;
    private javax.swing.JTextField jTextIdContratoAlq;
    private javax.swing.JTextField jTextMontoPesosContratoAlq;
    private javax.swing.JTextField jTextTelefonosPro3;
    private inmobiliaria23.entidades.BotonNegro jbBuscar;
    private inmobiliaria23.entidades.BotonRojo jbEliminar;
    private inmobiliaria23.entidades.BotonVerde jbGuardar;
    private inmobiliaria23.entidades.BotonNegro jbLimpiar;
    private inmobiliaria23.entidades.BotonNegro jbModificar;
    private inmobiliaria23.entidades.BotonAzul jbSalir;
    private inmobiliaria23.entidades.BotonNegro jbtnAñadir;
    // End of variables declaration//GEN-END:variables
}
