package inmobiliaria23.vistas;

import inmobiliaria23.accesoaDatos.PropiedadInmuebleData;
import inmobiliaria23.accesoaDatos.conexion;
import inmobiliaria23.entidades.InternaljFrameImagen;
import inmobiliaria23.entidades.PropiedadInmueble;
import inmobiliaria23.entidades.panelesImagenes;
import java.awt.Color;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class registroInmueble extends InternaljFrameImagen {

    private FileInputStream fis;
    private int longitudBytes;
    private panelesImagenes pi = new panelesImagenes();
    private PropiedadInmuebleData PropieData = new PropiedadInmuebleData();
    private PropiedadInmueble PropieActual = null;

    public registroInmueble() {
        initComponents();
        this.setSize(1024, 770);

        this.setImage("/inmobiliaria23/recursos/fondoMadera.jpg");
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextID = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        DatosInquilinos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextZona = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextAccesibilidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextDisponibilidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextSuperficie = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextPrecioBase = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextCaracteristicas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxTipos = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jbtnAñadir = new inmobiliaria23.entidades.BotonNegro();
        jbModificar = new inmobiliaria23.entidades.BotonNegro();
        jbLimpiar = new inmobiliaria23.entidades.BotonNegro();
        jbBuscar = new inmobiliaria23.entidades.BotonNegro();
        jbEliminar = new inmobiliaria23.entidades.BotonRojo();
        BTNGuardar = new inmobiliaria23.entidades.BotonVerde();
        NombrePropietario = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txt_nombre = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BTNSalir = new inmobiliaria23.entidades.BotonAzul();

        jTextID.setBackground(new java.awt.Color(236, 226, 200));
        jTextID.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextID.setForeground(new java.awt.Color(51, 51, 51));
        jTextID.setText(" ");
        jTextID.setBorder(null);
        jTextID.setPreferredSize(new java.awt.Dimension(165, 30));

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Roboto Bk", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(51, 51, 51));
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/inmueble-50.png"))); // NOI18N
        Titulo.setText("Registrar Inmuebles");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        DatosInquilinos.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        DatosInquilinos.setOpaque(false);
        DatosInquilinos.setPreferredSize(new java.awt.Dimension(500, 390));
        DatosInquilinos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel1.setText("ID:");
        DatosInquilinos.add(jLabel1);

        jTextId.setBackground(new java.awt.Color(236, 226, 200));
        jTextId.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextId.setForeground(new java.awt.Color(51, 51, 51));
        jTextId.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));
        jTextId.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos.add(jTextId);

        jLabel2.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel2.setText("Dirección:");
        DatosInquilinos.add(jLabel2);

        jTextDireccion.setBackground(new java.awt.Color(236, 226, 200));
        jTextDireccion.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextDireccion.setForeground(new java.awt.Color(51, 51, 51));
        jTextDireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));
        jTextDireccion.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos.add(jTextDireccion);

        jLabel3.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel3.setText("Zona:");
        DatosInquilinos.add(jLabel3);

        jTextZona.setBackground(new java.awt.Color(236, 226, 200));
        jTextZona.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextZona.setForeground(new java.awt.Color(51, 51, 51));
        jTextZona.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));
        jTextZona.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos.add(jTextZona);

        jLabel4.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel4.setText("Accesibilidad:");
        DatosInquilinos.add(jLabel4);

        jTextAccesibilidad.setBackground(new java.awt.Color(236, 226, 200));
        jTextAccesibilidad.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextAccesibilidad.setForeground(new java.awt.Color(51, 51, 51));
        jTextAccesibilidad.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));
        jTextAccesibilidad.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos.add(jTextAccesibilidad);

        jLabel5.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel5.setText("Disponibildad:");
        DatosInquilinos.add(jLabel5);

        jTextDisponibilidad.setBackground(new java.awt.Color(236, 226, 200));
        jTextDisponibilidad.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextDisponibilidad.setForeground(new java.awt.Color(51, 51, 51));
        jTextDisponibilidad.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));
        jTextDisponibilidad.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos.add(jTextDisponibilidad);

        jLabel12.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel12.setText("Superficie:");
        DatosInquilinos.add(jLabel12);

        jTextSuperficie.setBackground(new java.awt.Color(236, 226, 200));
        jTextSuperficie.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextSuperficie.setForeground(new java.awt.Color(51, 51, 51));
        jTextSuperficie.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));
        jTextSuperficie.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos.add(jTextSuperficie);

        jLabel13.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel13.setText("Precio Base:");
        DatosInquilinos.add(jLabel13);

        jTextPrecioBase.setBackground(new java.awt.Color(236, 226, 200));
        jTextPrecioBase.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextPrecioBase.setForeground(new java.awt.Color(51, 51, 51));
        jTextPrecioBase.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));
        jTextPrecioBase.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos.add(jTextPrecioBase);

        jLabel14.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel14.setText("Características:");
        DatosInquilinos.add(jLabel14);

        jTextCaracteristicas.setBackground(new java.awt.Color(236, 226, 200));
        jTextCaracteristicas.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextCaracteristicas.setForeground(new java.awt.Color(51, 51, 51));
        jTextCaracteristicas.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray));
        jTextCaracteristicas.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos.add(jTextCaracteristicas);

        jLabel15.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel15.setText("Tipo:");
        DatosInquilinos.add(jLabel15);

        jComboBoxTipos.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jComboBoxTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "items1", "items2..." }));
        jComboBoxTipos.setBorder(null);
        jComboBoxTipos.setPreferredSize(new java.awt.Dimension(100, 35));
        DatosInquilinos.add(jComboBoxTipos);

        getContentPane().add(DatosInquilinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 190, 550));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jbtnAñadir.setBorder(null);
        jbtnAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/nuevo.png"))); // NOI18N
        jbtnAñadir.setText(" NUEVO");
        jbtnAñadir.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jbtnAñadir.setPreferredSize(new java.awt.Dimension(120, 30));
        jbtnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAñadir);

        jbModificar.setBorder(null);
        jbModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/modificar.png"))); // NOI18N
        jbModificar.setText(" MODIFICAR");
        jbModificar.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jbModificar.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel1.add(jbModificar);

        jbLimpiar.setBorder(null);
        jbLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/LimpiarCampos.png"))); // NOI18N
        jbLimpiar.setText(" LIMPIAR");
        jbLimpiar.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jbLimpiar.setPreferredSize(new java.awt.Dimension(120, 30));
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jbLimpiar);

        jbBuscar.setBorder(null);
        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/buscar-interna.png"))); // NOI18N
        jbBuscar.setText(" BUSCAR");
        jbBuscar.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jbBuscar.setPreferredSize(new java.awt.Dimension(120, 30));
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jbBuscar);

        jbEliminar.setBorder(null);
        jbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/delete.png"))); // NOI18N
        jbEliminar.setText("ELIMINAR");
        jbEliminar.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jbEliminar.setPreferredSize(new java.awt.Dimension(120, 30));
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jbEliminar);

        BTNGuardar.setBorder(null);
        BTNGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/guardar.png"))); // NOI18N
        BTNGuardar.setText("GUARDAR");
        BTNGuardar.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        BTNGuardar.setPreferredSize(new java.awt.Dimension(120, 30));
        BTNGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(BTNGuardar);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1000, 50));

        NombrePropietario.setFont(new java.awt.Font("Roboto Cn", 1, 12)); // NOI18N
        NombrePropietario.setForeground(new java.awt.Color(0, 0, 0));
        NombrePropietario.setText("Del propietario de: Fulano de tal");
        getContentPane().add(NombrePropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        jPanel4.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.add(txt_nombre);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 660, 170, 40));

        jPanel5.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 710, 490));

        BTNSalir.setBorder(null);
        BTNSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/exits.png"))); // NOI18N
        BTNSalir.setText(" SALIR");
        BTNSalir.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        BTNSalir.setPreferredSize(new java.awt.Dimension(120, 30));
        BTNSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BTNSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 660, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAñadirActionPerformed
        //NuevoInmueble();
    }//GEN-LAST:event_jbtnAñadirActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        //BuscarInmueble();

    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed

    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        jTextId.setText("");
        jTextDireccion.setText("");
        jTextZona.setText("");
        jTextAccesibilidad.setText("");
        jTextDisponibilidad.setText("");

    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void BTNGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGuardarActionPerformed
        //GuardarImagen();
    }//GEN-LAST:event_BTNGuardarActionPerformed

    private void BTNSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BTNSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private inmobiliaria23.entidades.BotonVerde BTNGuardar;
    private inmobiliaria23.entidades.BotonAzul BTNSalir;
    private javax.swing.JPanel DatosInquilinos;
    private javax.swing.JLabel NombrePropietario;
    private javax.swing.JLabel Titulo;
    private javax.swing.JComboBox<String> jComboBoxTipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextAccesibilidad;
    private javax.swing.JTextField jTextCaracteristicas;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextDisponibilidad;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextPrecioBase;
    private javax.swing.JTextField jTextSuperficie;
    private javax.swing.JTextField jTextZona;
    private inmobiliaria23.entidades.BotonNegro jbBuscar;
    private inmobiliaria23.entidades.BotonRojo jbEliminar;
    private inmobiliaria23.entidades.BotonNegro jbLimpiar;
    private inmobiliaria23.entidades.BotonNegro jbModificar;
    private inmobiliaria23.entidades.BotonNegro jbtnAñadir;
    private javax.swing.JLabel txt_nombre;
    // End of variables declaration//GEN-END:variables

    public void BuscarInmueble() {
        int inmuebleActual;
        try {
            Integer id = Integer.parseInt(jTextId.getText());
            double parbase = Double.parseDouble(jTextPrecioBase.getText());

            PropieActual = PropieData.buscarInmuebleXid(id);
            if (PropieActual != null) {

                jTextDireccion.setText(PropieActual.getDireccion());
                jTextZona.setText(PropieActual.getZona());
                jTextAccesibilidad.setText(PropieActual.getZona());
                jTextDisponibilidad.setText(PropieActual.getZona());

                jTextSuperficie.setText(PropieActual.getZona());
                jTextCaracteristicas.setText(PropieActual.getCaracteristicas());

            }
        } catch (NumberFormatException ex) {
            String mensaje = "Debes Ingresar un ID para buscar";
            MensajeEmergentesAdvertencias me = new MensajeEmergentesAdvertencias(null, true);
            me.TextoMensaje(mensaje);
            me.setVisible(true);
        }

    }

    public void NuevoInmueble() {
        Limpiar();
        PropieActual = null;
        
        
    }
//metodo para guardar
//    public void GuardarImagen() {
//
//        if (txt_nombre.getText().equals(" ")) {
//            txt_nombre.setBackground(Color.red);
//            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
//        } else {
//
//            String nombre;
//            nombre = txt_nombre.getText().trim();
//
//            try {
//
//                Connection cn = conexion.conectar();
//                PreparedStatement pst = cn.prepareStatement("INSERT INTO imagenes (id_foto,nombre,foto) values (?,?,?)");
//
//                pst.setInt(1, 0);
//                pst.setString(2, nombre);
//                pst.setBlob(3, fis, longitudBytes);
//
//                pst.executeUpdate();
//                cn.close();
//                Limpiar();
//                txt_nombre.setBackground(Color.green);
//                //jLabel_foto.setText("foto");
//                mensajeCorrecto msCorrecto = new mensajeCorrecto(null, true);
//                msCorrecto.setVisible(true);
//
//            } catch (SQLException e) {
//                System.out.println("Error al guardar foto " + e.getMessage());
//                JOptionPane.showMessageDialog(null, "¡¡Error al guardar foto!!");
//            }
//
//        }
//    }
//
//    //metodo Limpiar
    public void Limpiar() {
        jTextId.setText("");
        jTextDireccion.setText("");
        jTextZona.setText("");
        jTextAccesibilidad.setText("");
        jTextDisponibilidad.setText("");

    }

}
