package inmobiliaria23.vistas;

import inmobiliaria23.entidades.InternaljFrameImagen;
import inmobiliaria23.entidades.panelesImagenes;
import java.awt.Image;

/**
 *
 * @author Administrador
 */
public class registroInmueble extends InternaljFrameImagen {

    private panelesImagenes pi = new panelesImagenes();

    public registroInmueble() {
        initComponents();
        this.setSize(1024, 770);

        this.setImage("/inmobiliaria23/recursos/fondoMadera.jpg");
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextID = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        DatosInquilinos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextDni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextCuit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextNombreApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextLugarTrabajo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jbtnAñadir = new inmobiliaria23.entidades.BotonNegro();
        jbModificar = new inmobiliaria23.entidades.BotonNegro();
        jbLimpiar1 = new inmobiliaria23.entidades.BotonNegro();
        jbLimpiar = new inmobiliaria23.entidades.BotonNegro();
        jbEliminar = new inmobiliaria23.entidades.BotonRojo();
        botonVerde1 = new inmobiliaria23.entidades.BotonVerde();
        botonAzul1 = new inmobiliaria23.entidades.BotonAzul();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextTlefonos3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextTlefonos6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextTlefonos7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        NombrePropietario = new javax.swing.JLabel();

        jTextID.setBackground(new java.awt.Color(236, 226, 200));
        jTextID.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextID.setForeground(new java.awt.Color(51, 51, 51));
        jTextID.setText(" ");
        jTextID.setBorder(null);
        jTextID.setPreferredSize(new java.awt.Dimension(165, 30));

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Roboto Bk", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(51, 51, 51));
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/inmueble-50.png"))); // NOI18N
        Titulo.setText("Registrar Inmuebles");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        DatosInquilinos.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        DatosInquilinos.setOpaque(false);
        DatosInquilinos.setPreferredSize(new java.awt.Dimension(500, 390));
        DatosInquilinos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel1.setText("ID:");
        DatosInquilinos.add(jLabel1);

        jTextId.setBackground(new java.awt.Color(236, 226, 200));
        jTextId.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextId.setForeground(new java.awt.Color(51, 51, 51));
        jTextId.setText(" ");
        jTextId.setBorder(null);
        jTextId.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos.add(jTextId);

        jLabel2.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel2.setText("Dirección:");
        DatosInquilinos.add(jLabel2);

        jTextDni.setBackground(new java.awt.Color(236, 226, 200));
        jTextDni.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextDni.setForeground(new java.awt.Color(51, 51, 51));
        jTextDni.setText(" ");
        jTextDni.setBorder(null);
        jTextDni.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos.add(jTextDni);

        jLabel3.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel3.setText("Zona:");
        DatosInquilinos.add(jLabel3);

        jTextCuit.setBackground(new java.awt.Color(236, 226, 200));
        jTextCuit.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextCuit.setForeground(new java.awt.Color(51, 51, 51));
        jTextCuit.setText(" ");
        jTextCuit.setBorder(null);
        jTextCuit.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos.add(jTextCuit);

        jLabel4.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel4.setText("Accesibilidad:");
        DatosInquilinos.add(jLabel4);

        jTextNombreApellido.setBackground(new java.awt.Color(236, 226, 200));
        jTextNombreApellido.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextNombreApellido.setForeground(new java.awt.Color(51, 51, 51));
        jTextNombreApellido.setText(" ");
        jTextNombreApellido.setBorder(null);
        jTextNombreApellido.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos.add(jTextNombreApellido);

        jLabel5.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel5.setText("Disponibildad:");
        DatosInquilinos.add(jLabel5);

        jTextLugarTrabajo.setBackground(new java.awt.Color(236, 226, 200));
        jTextLugarTrabajo.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextLugarTrabajo.setForeground(new java.awt.Color(51, 51, 51));
        jTextLugarTrabajo.setText(" ");
        jTextLugarTrabajo.setBorder(null);
        jTextLugarTrabajo.setPreferredSize(new java.awt.Dimension(165, 30));
        DatosInquilinos.add(jTextLugarTrabajo);

        getContentPane().add(DatosInquilinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 190, 320));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jbtnAñadir.setBorder(null);
        jbtnAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/nuevo.png"))); // NOI18N
        jbtnAñadir.setText(" NUEVO");
        jbtnAñadir.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jbtnAñadir.setPreferredSize(new java.awt.Dimension(120, 30));
        jbtnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAñadir);

        jbModificar.setBorder(null);
        jbModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/modificar.png"))); // NOI18N
        jbModificar.setText(" MODIFICAR");
        jbModificar.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jbModificar.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel1.add(jbModificar);

        jbLimpiar1.setBorder(null);
        jbLimpiar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/LimpiarCampos.png"))); // NOI18N
        jbLimpiar1.setText(" LIMPIAR");
        jbLimpiar1.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jbLimpiar1.setPreferredSize(new java.awt.Dimension(120, 30));
        jbLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbLimpiar1);

        jbLimpiar.setBorder(null);
        jbLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/buscar-interna.png"))); // NOI18N
        jbLimpiar.setText(" BUSCAR");
        jbLimpiar.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jbLimpiar.setPreferredSize(new java.awt.Dimension(120, 30));
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jbLimpiar);

        jbEliminar.setBorder(null);
        jbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/delete.png"))); // NOI18N
        jbEliminar.setText("ELIMINAR");
        jbEliminar.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jbEliminar.setPreferredSize(new java.awt.Dimension(120, 30));
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jbEliminar);

        botonVerde1.setBorder(null);
        botonVerde1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/guardar.png"))); // NOI18N
        botonVerde1.setText("GUARDAR");
        botonVerde1.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        botonVerde1.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel1.add(botonVerde1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1000, 50));

        botonAzul1.setBorder(null);
        botonAzul1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inmobiliaria23/recursos/exits.png"))); // NOI18N
        botonAzul1.setText(" SALIR");
        botonAzul1.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        botonAzul1.setPreferredSize(new java.awt.Dimension(120, 30));
        botonAzul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAzul1ActionPerformed(evt);
            }
        });
        getContentPane().add(botonAzul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 560, -1, -1));

        jPanel2.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel7.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel7.setText("Superficie:");
        jPanel2.add(jLabel7);

        jTextTlefonos3.setBackground(new java.awt.Color(236, 226, 200));
        jTextTlefonos3.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextTlefonos3.setForeground(new java.awt.Color(51, 51, 51));
        jTextTlefonos3.setText(" ");
        jTextTlefonos3.setBorder(null);
        jTextTlefonos3.setPreferredSize(new java.awt.Dimension(165, 30));
        jPanel2.add(jTextTlefonos3);

        jLabel8.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel8.setText("Precio Base:");
        jPanel2.add(jLabel8);

        jTextTlefonos6.setBackground(new java.awt.Color(236, 226, 200));
        jTextTlefonos6.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextTlefonos6.setForeground(new java.awt.Color(51, 51, 51));
        jTextTlefonos6.setText(" ");
        jTextTlefonos6.setBorder(null);
        jTextTlefonos6.setPreferredSize(new java.awt.Dimension(165, 30));
        jPanel2.add(jTextTlefonos6);

        jLabel9.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel9.setText("Características:");
        jPanel2.add(jLabel9);

        jTextTlefonos7.setBackground(new java.awt.Color(236, 226, 200));
        jTextTlefonos7.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jTextTlefonos7.setForeground(new java.awt.Color(51, 51, 51));
        jTextTlefonos7.setText(" ");
        jTextTlefonos7.setBorder(null);
        jTextTlefonos7.setPreferredSize(new java.awt.Dimension(165, 30));
        jPanel2.add(jTextTlefonos7);

        jLabel10.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel10.setText("Tipo:");
        jPanel2.add(jLabel10);

        jComboBox1.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "items1", "items2..." }));
        jComboBox1.setBorder(null);
        jComboBox1.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel2.add(jComboBox1);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 210, 290));

        jPanel3.setBackground(new java.awt.Color(236, 226, 200));
        jPanel3.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 460, 360));

        jLabel11.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel11.setText("Imagen Inmueble:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        NombrePropietario.setFont(new java.awt.Font("Roboto Cn", 1, 12)); // NOI18N
        NombrePropietario.setForeground(new java.awt.Color(0, 0, 0));
        NombrePropietario.setText("Del propietario de: Fulano de tal");
        getContentPane().add(NombrePropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAñadirActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
       

    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void botonAzul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAzul1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_botonAzul1ActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed

    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiar1ActionPerformed
        jTextId.setText("");
        jTextDni.setText("");
        jTextCuit.setText("");
        jTextNombreApellido.setText("");
        jTextLugarTrabajo.setText("");
        
    }//GEN-LAST:event_jbLimpiar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DatosInquilinos;
    private javax.swing.JLabel NombrePropietario;
    private javax.swing.JLabel Titulo;
    private inmobiliaria23.entidades.BotonAzul botonAzul1;
    private inmobiliaria23.entidades.BotonVerde botonVerde1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextCuit;
    private javax.swing.JTextField jTextDni;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextLugarTrabajo;
    private javax.swing.JTextField jTextNombreApellido;
    private javax.swing.JTextField jTextTlefonos3;
    private javax.swing.JTextField jTextTlefonos6;
    private javax.swing.JTextField jTextTlefonos7;
    private inmobiliaria23.entidades.BotonRojo jbEliminar;
    private inmobiliaria23.entidades.BotonNegro jbLimpiar;
    private inmobiliaria23.entidades.BotonNegro jbLimpiar1;
    private inmobiliaria23.entidades.BotonNegro jbModificar;
    private inmobiliaria23.entidades.BotonNegro jbtnAñadir;
    // End of variables declaration//GEN-END:variables
}
